In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Load data
train_df = pd.read_csv('train_nurse.csv')
test_df = pd.read_csv('test_nurse.csv', index_col='ID')

train_df.head()

   aline_flg       age  gender_num  ...  po2_first  pco2_first     iv_day_1
0          1  72.36841         1.0  ...      196.0        39.0  2230.875000
1          0  48.40044         0.0  ...      473.0        32.0  2850.000000
2          1  48.97547         1.0  ...      493.0        34.0  3682.880127
3          1  60.37829         0.0  ...      473.0        34.0   213.119995
4          1  83.20917         1.0  ...      251.0        35.0          NaN

[5 rows x 40 columns]

In [ ]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1335 entries, 0 to 1334
Data columns (total 40 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   aline_flg           1335 non-null   int64
 1   age                 1335 non-null   float64
 2   gender_num          1334 non-null   float64
 3   weight_first        1255 non-null   float64
 4   bmi                 1001 non-null   float64
 5   sapsi_first         1335 non-null   int64
 6   sofa_first          1335 non-null   int64
 7   service_unit        1335 non-null   object
 8   service_num         1335 non-null   int64
 9   day_icu_intime      1335 non-null   object
 10  day_icu_intime_num  1335 non-null   int64
 11  hour_icu_intime     1335 non-null   int64
 12  day_28_flg          100 non-null    float64
 13  sepsis_flg          1335 non-null   int64
 14  chf_flg             1335 non-null   int64
 15  afib_flg            1335 non-null   int64
 16  renal_flg           1335 non-null   int64
 17  liver_flg           1335 non-null   int64
 18  copd_flg            1335 non-null   int64
 19  cad_flg             1335 non-null   int64
 20  stroke_flg          1335 non-null   int64
 21  mal_flg             1335 non-null   int64
 22  resp_flg            1335 non-null   int64
 23  map_1st             1335 non-null   float64
 24  hr_1st              1335 non-null   int64
 25  temp_1st            1335 non-null   float64
 26  spo2_1st            1335 non-null   int64
 27  abg_count           1335 non-null   int64
 28  wbc_first           1334 non-null   float64
 29  hgb_first           1333 non-null   float64
 30  platelet_first      1334 non-null   float64
 31  sodium_first        1334 non-null   float64
 32  potassium_first     1334 non-null   float64
 33  tco2_first          1334 non-null   float64
 34  chloride_first      1334 non-null   float64
 35  bun_first           1334 non-null   float64
 36  creatinine_first    1333 non-null   float64
 37  po2_first           1222 non-null   float64
 38  pco2_first          1222 non-null   float64
 39  iv_day_1            1246 non-null   float64
dtypes: float64(19), int64(19), object(2)
memory usage: 417.3+ KB

# Subtasks 1-2

In [ ]:
#Subtask 1
answer_sub1 = dict(train_df.isna().sum()).get('day_28_flg')

#Subtask 2
def subtask2(df):
    df = df.copy()
    df = df.dropna(subset=['day_28_flg'])

    group1 = df[df['sofa_first'] > 10]
    group2 = df[df['sofa_first'] <= 10]

    mortality1 = (group1['day_28_flg'].mean()) * 100
    mortality2 = (group2['day_28_flg'].mean()) * 100
    return [mortality1, mortality2]

answer_sub2 = subtask2(train_df)

# Subtask 3

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC

train_df = train_df.dropna(subset='day_28_flg')
X = train_df.drop('day_28_flg', axis=1)
y = train_df['day_28_flg']

#Preparations
X, test_df = X.drop('day_icu_intime_num', axis=1), test_df.drop('day_icu_intime_num', axis=1)

num_cols = X.select_dtypes(include=[np.number]).columns
cat_cols = X.select_dtypes(include=['object']).columns

def make_preprocessor():
    num_transformer = Pipeline(steps=[
        ('imputer', KNNImputer()),
        ('scaler', StandardScaler())
    ])
    cat_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('encoder', OneHotEncoder(sparse_output=False))
    ])

    preprocessor = ColumnTransformer(transformers=[
        ('num', num_transformer, num_cols),
        ('cat', cat_transformer, cat_cols),
    ],  verbose_feature_names_out=False)

    return preprocessor

preprocessor = make_preprocessor()

X_transformed, test_transformed = preprocessor.fit_transform(X), preprocessor.transform(test_df)
model = SVC(probability=True, random_state=42, C=0.6)  
model.fit(X_transformed, y)
preds = model.predict_proba(test_transformed)[:,1]

In [ ]:
#Submission now

output_df = pd.DataFrame({
    'subtaskID':[1,2,2] + [3] * len(test_df),
    'datapointID':[1,1,2] + list(test_df.index),
    'answer':[answer_sub1] + answer_sub2 + list(preds)
})

output_df.head()

   subtaskID  datapointID       answer
0          1            1  1235.000000
1          2            1     0.000000
2          2            2    51.020408
3          3            0     0.228730
4          3            1     0.838892

In [ ]:
output_df.to_csv('submission.csv', index=False)

This aproach works surprisingly well (90/100)

The intended solution is to do pseudo-labeling.